# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on:
  push:
    branches:
      - fe/dev # ← 오직 fe/dev 브랜치에 push될 때만 트리거

jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: yarn

      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
