name: Chromatic Deployment

on:
  pull_request:
    branches: [fe/dev]
  push:
    branches: [fe/dev]

# 두 워크플로우 동시 실행 방지
concurrency:
  group: chromatic-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Chromatic Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./frontend/yarn.lock') }}

      - run: yarn
        working-directory: ./frontend

      # 내부 리포지토리 PR/push일 때만 Chromatic 실행
      - if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        uses: chromaui/action@latest
        with:
          workingDir: ./frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
